export const ALL_GRAB_REQUEST = "ALL_GRAB_REQUEST";
export const ALL_GRAB_SUCCESS = "ALL_GRAB_SUCCESS";
export const ALL_GRAB_FAIL = "ALL_GRAB_FAIL";

export const SINGLE_GRAB_REQUEST = "SINGLE_GRAB_REQUEST";
export const SINGLE_GRAB_SUCCESS = "SINGLE_GRAB_SUCCESS";
export const SINGLE_GRAB_FAIL = "SINGLE_GRAB_FAIL";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";

export const POST_GRAB_REQUEST = "POST_GRAB_REQUEST";
export const POST_GRAB_SUCCESS = "POST_GRAB_SUCCESS";
export const POST_GRAB_FAIL = "POST_GRAB_FAIL";
